### ISSUE TITLE
Incorrect function argument 

### ISSUE THREAD

**Issue by C-Loftus** [infapi00/at-spi2-examples#13]
https://github.com/infapi00/at-spi2-examples/blob/3602f873480680a9a564f7654ee382007af415e4/javascript/dump-tree.js#L51

I believe that `node` should not be passed into the `get_child_count()` function. This function does not take an argument.

```
Gjs-Message: 23:54:02.955: JS WARNING: [test.js 49]: Too many arguments to method Atspi.Accessible.get_child_count: expected 0, got 1
```

Realize this repository and example are very old but I wanted to list it here since there are very few other good atspi examples published.
Thanks for your work!

**Comment by infapi00** [comment]
> Gjs-Message: 23:54:02.955: JS WARNING: [test.js 49]: Too many arguments to method Atspi.Accessible.get_child_count: expected 0, got 1

Seems that now gjs has more warnings, that is nice. Just fixed with this https://github.com/infapi00/at-spi2-examples/pull/14

> Realize this repository and example are very old

Well, this is mostly a repository with examples, the idea is not adding a lot of features of stuff too complex, so the idea is not needing a lot of updates (but suggestions/patches are welcome). In fact it was debated now and then to move these to the projects doing the real stuff (like at-spi2). The problem with that is adding python/javascript code to those repositories.

> Thanks for your work!

Thanks for reporting!
